# Generated by Django 5.0 on 2024-02-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=25)),
                ('date', models.DateField(max_length=15)),
                ('time', models.TimeField(max_length=15)),
                ('tickets', models.IntegerField()),
            ],
        ),
    ]
