# Generated by Django 5.1.1 on 2024-11-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tickets',
            new_name='capacity',
        ),
    ]
